### ISSUE TITLE
`remove()` doesn't seem to work on `node`es

### ISSUE THREAD

**Issue by sindresorhus** [millermedeiros/rocambole-token#2]
I tried this:

``` js
var rocambole = require('rocambole');
var token = require('rocambole-token');

console.log(rocambole.moonwalk(rocambole.parse('function foo(){debugger;}'), function (node) {
    if (node.type === 'DebuggerStatement') {
        token.remove(node);
    }
}).toString());

//=> function foo(){debugger;}
```

I would have expected it to remove the debugger statement.

However, this seems to work:

``` js
var rocambole = require('rocambole');
var token = require('rocambole-token');

console.log(rocambole.moonwalk(rocambole.parse('function foo(){debugger;}'), function (node) {
    if (node.type === 'DebuggerStatement') {
        var currentToken = node.startToken;

        while (currentToken !== node.endToken.next) {
            token.remove(currentToken);
            currentToken = currentToken.next;
        }
    }
}).toString());

//=> function foo(){}
```

But manual labor isn't fun.

**Comment by millermedeiros** [comment]
the `remove()` on `rocambole-token` only removes tokens. the [rocambole-node](https://github.com/millermedeiros/rocambole-node) module will have methods for manipulating the AST itself but it still doesn't have a `remove` method.

a _simple_ way to remove all the tokens from a node is to: `token.eachInBetween(node.startToken, node.endToken, token.remove)`

**Comment by millermedeiros** [comment]
another way would be to remove the links like:

``` js
function removeNodeContent(node){
  var prev = node.startToken.prev;
  var next = node.endToken.next;
  node.startToken = prev;
  prev.next = next;
  next.prev = prev;
  node.endToken = next;
}
```

that way the `ast.toString` would not include any content from the node (even tho it would still be part of the AST).
